### ISSUE TITLE
[FEAT] 로그인, 약관 동의, 회원가입  퍼블리싱

### ISSUE THREAD

**Issue by Jieun-KWAK** [woorifisa-projects-3rd/woori-zip-FE#23]
### 💬 기능 설명
> 로그인, 약관 동의, 회원가입 퍼블리싱 진행

### 🎯 구현 내용
- [ ] 로그인, 약관 동의, 회원가입 경로 확인
- [ ] 수정된 로그인 인트로 페이지 초안 완성
- [ ]  사용자/관리자 페이지에서도 Tab 사용할 수 있도록 component폴더 안에 atoms 생성하여 올리기
- [ ] 구현 페이지에 필요한 이미지 추가

**Comment by LouiIII3** [comment]
확인했습니다~
