### ISSUE TITLE
[REFACTOR] 페이지 라우팅 및 로그인 로직 수정

### ISSUE THREAD

**Issue by LouiIII3** [woorifisa-projects-3rd/woori-zip-FE#97]
### 💬 기능 설명
> 메인페이지의 라우팅과 로그인 부분 수정입니다.

### 🎯 구현 내용
- [x] 메인페이지 라우팅
- [x] 지도페이지 라우팅
- [x] 로그인 정보 수정

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Implemented main page and map page routing, updated login information handling, and adjusted the Header component for better user flow.

You can review changes in this commit: https://github.com/jjyutm4532/woorifisa-projects-3rd-woori-zip-FE-97/commit/9f43ce58f14ac535997fca67e51731b145f38824.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by LouiIII3** [comment]
라우터 연결 완료되었습니다.
